version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: online-courses-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: online_courses

volumes:
  mongo_data:
